### ISSUE TITLE
collapse_pangoro() does not collapse strains with aliases of exactly three generations.

### ISSUE THREAD

**Issue by sydprudko** [al-obrien/pangoRo#1]
```
my_pangoro <- pangoRo::pangoro()

pangoRo::collapse_pangoro(my_pangoro, "XBB.1.9.2.2")
 "EG.2"
pangoRo::collapse_pangoro(my_pangoro, "XBB.1.9.2")
 "XBB.1.9.2"

pangoRo::collapse_pangoro(my_pangoro, "XBB.1.9.2.5.1.1")
"EG.5.1.1"
pangoRo::collapse_pangoro(my_pangoro, "XBB.1.9.2.5.1.1.3")
 "HK.3"

```

An option for XBB.1.9.2, when collapsed, to return alias EG instead of the complete strain name would be useful for presenting data to understand the relatedness of strains and their descendants, or if there is a desire to group to a higher order parent lineage.

**Comment by al-obrien** [comment]
Should be fixed in f7bef168cdc28a9c3cc94e133fe26e815ffeee7b along with a few other bugs found along the way, closing. New examples show how to use the new parameter.
